import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Navbar from '../components/Navbar'
import Dashboard from '../components/Dashboard'
import CreateAdmin from '../components/createAdmin'
import { useState, useEffect } from 'react'
import ValidateUsers from '../components/ValidateUsers'
import UsersList from '../components/UsersList'
import { apiService } from '../services/APIService'

export default function Home() {

  const [dashboard, setDashboard] = useState(true)
  const [createAdmin, setCreateAdmin] = useState(false)
  const [validateUsers, setValidateUsers] = useState(false)
  const [usersList, setUsersList] = useState(false)
  const [users, setUsers] = useState([])

  useEffect(() => {
    apiService.get('users')
      .then(
        response => setUsers(response.data)
      )
  }, [usersList])

  const setAllToFalse = () => {
    setDashboard(false)
    setCreateAdmin(false)
    setValidateUsers(false)
    setUsersList(false)
  }

  const switchToDashboard = () => {
    setAllToFalse()
    setDashboard(true)
  }

  const switchToCreateAdmin = () => {
    setAllToFalse()
    setCreateAdmin(true)
  }

  const switchToValidateUsers = () => {
    setAllToFalse()
    setValidateUsers(true)
  }

  const switchToUsersList = () => {
    setAllToFalse()
    setUsersList(true)
  }


  return (
    <>
      <Head>
        <title className={styles.title}>Dashboard - CSE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className={styles.main}>
        <Navbar
          switchToDashboard={switchToDashboard}
          switchToCreateAdmin={switchToCreateAdmin}
          switchToValidateUsers={switchToValidateUsers}
          switchToUsersList={switchToUsersList}
        />
        {dashboard ? (<Dashboard />) : ('')}
        {createAdmin ? (<CreateAdmin />) : ('')}
        {validateUsers ? (<ValidateUsers />) : ('')}
        {usersList ? (<UsersList users={users} />) : ('')}
      </main>

      <footer className={styles.footer}>
      </footer>
    </>
  )
}

// export async function getStaticProps() {
//   const res = await fetch('http://localhost:5000/api/users')
//   const users = await res.json()

//   return {
//     props: {
//       users,
//     },
//   }
// }